name: CMake Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v1.7.0
    
    - name: Install Dependencies
      shell: bash -l {0}
      run: conda install cmake xtl xproperty nlohmann_json -c conda-forge

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    
    - name: Check Environment
      shell: bash -l {0}
      run: conda info

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      shell: bash -l {0}
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDOWNLOAD_GTEST=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash -l {0}
      run: cmake --build . --config $BUILD_TYPE --target install

    - name: Run Tests Windows
      if: matrix.os == 'windows-latest'
      working-directory: ${{runner.workspace}}/build/test/Release
      shell: bash -l {0}
      run: ./test_xvega_lib.exe

    - name: Run Tests Unix
      if: matrix.os != 'window-latest'
      working-directory: ${{runner.workspace}}/build/test
      shell: bash -l {0}
      run: ./test_xvega_lib
